/// Trimmed planet-generation params: only the fields the elevation, climate,
/// and hydrology pipeline actually consumes. No per-species, atmosphere, or
/// region-detection generality — Earth-like/human is the only target.
pub struct PlanetGenParams {
    pub warp_strength: f64,
    pub sea_level: f64,
    pub axial_tilt: f64,
    pub temp_baseline: f64,
    pub temp_gradient: f64,
    pub lapse_factor: f64,
    pub sea_ice_evap_factor: f64,
    pub precip_moisture: f64,
    pub land_decay: f64,
    pub slope_threshold: f64,
    pub slope_loss: f64,
    pub base_arid: f64,
    pub et_factor: f64,
    pub rotation_period: f64,
    pub glacier_temp_threshold: f64,
    pub sea_ice_temp_threshold: f64,
    pub max_lake_fill: f64,
    pub river_threshold: f64,
    pub aquifer_probability: f64,
    pub glacier_melt_factor: f64,
    pub radius_km: f64,
    pub land_threshold: f64,
    pub ocean_threshold: f64,
    pub region_min_size: usize,
    pub island_coast_dist: usize,
    pub island_arch_dist: usize,
    pub lon_weight: f64,
    pub current_temp_bias: f64,
    pub current_search_dist: usize,
    pub current_bleed_dist: usize,
    // Freshwater greening (render-only vegetation shift, not a climate change)
    pub greening_radius: usize,
    pub greening_aquifer_strength: f64,
    pub greening_ocean_damp_dist: usize,
    pub greening_strength: f64,
    pub greening_temp_floor: f64,
    pub greening_temp_full: f64,
    // Lake-effect climate (one-way, applied after hydrology)
    pub lake_effect_min_size: usize,
    pub lake_halo_dist: usize,
    pub lake_precip_boost: f64,
    pub lake_swing_damp: f64,
    // Coastline character (render-only)
    pub shore_mouth_radius: usize,
    pub shore_cliff_slope: f64,
}

impl PlanetGenParams {
    /// Earth-analog defaults, adapted from demiurge-rust's `PlanetParams::earth_like()`.
    pub fn earth_like() -> Self {
        Self {
            warp_strength: 0.2,
            sea_level: 0.525,
            axial_tilt: 23.5,
            temp_baseline: 1.0,
            temp_gradient: 1.0,
            lapse_factor: 0.3,
            sea_ice_evap_factor: 0.25,
            precip_moisture: 1.0,
            land_decay: 0.985,
            slope_threshold: 0.015,
            slope_loss: 0.5,
            base_arid: 0.05,
            et_factor: 0.35,
            rotation_period: 1.0,
            glacier_temp_threshold: 0.20,
            sea_ice_temp_threshold: 0.14,
            max_lake_fill: 0.04,
            river_threshold: 400.0,
            aquifer_probability: 0.35,
            glacier_melt_factor: 2.5,
            radius_km: 6371.0,
            land_threshold: 0.15,
            ocean_threshold: 0.59,
            region_min_size: 150,
            island_coast_dist: 3,
            island_arch_dist: 25,
            lon_weight: 0.82,
            current_temp_bias: 0.10,
            current_search_dist: 40,
            current_bleed_dist: 8,
            greening_radius: 6,
            greening_aquifer_strength: 0.4,
            greening_ocean_damp_dist: 5,
            greening_strength: 0.35,
            greening_temp_floor: 0.30,
            greening_temp_full: 0.45,
            lake_effect_min_size: 12,
            lake_halo_dist: 6,
            lake_precip_boost: 0.08,
            lake_swing_damp: 0.4,
            shore_mouth_radius: 3,
            shore_cliff_slope: 0.012,
        }
    }
}
